name: 'Deploy to AFFiNE Internal'
description: 'Deploy container to affine internal network'
branding:
    icon: 'arrow-right-circle'
    color: 'gray-dark'
inputs:
    tailscale_key:
        description: 'Your Tailscale authentication key, from the admin panel.'
        required: true
    nomad_addr:
        description: 'Nomad address.'
        required: true
    nomad_token:
        description: 'Nomad token.'
        required: true
    consul_addr:
        description: 'Consul address.'
        required: true
    consul_token:
        description: 'Consul token.'
        required: true
    config_file:
        description: 'The path to Nomad Pack config file.'
        required: false
        default: ''
    config:
        description: 'The Nomad Pack config.'
        required: false
        default: ''
runs:
    using: 'composite'
    steps:
        - name: Check network
          id: check_network
          shell: bash
          run: curl -s --connect-timeout 1 -m 2 ${{ inputs.nomad_addr }} > /dev/null || exit 1
          continue-on-error: true

        - name: Connect to Tailscale
          if: steps.check_network.outcome != 'success'
          uses: tailscale/github-action@ce41a99162202a647a4b24c30c558a567b926709
          with:
              authkey: ${{ inputs.tailscale_key }}
              version: 1.36.0

        - name: Setup `nomad-pack`
          uses: hashicorp/setup-nomad-pack@ea80f2bfbcb2f318e65207177a589f457933efc5
          with:
              version: 'v0.0.1-techpreview.3'

        - name: Deploy to AFFiNE Internal
          shell: bash
          run: |
              if [ "$NOMAD_CONFIG_FILE" != '' ]; then
                  nomad-pack run templates --name=deploy-actions -f ${{ inputs.config_file }}
              elif [ "$NOMAD_CONFIG" != '' ]; then
                  echo "$NOMAD_CONFIG" > ${{ runner.temp }}/config.hcl
                  nomad-pack run templates --name=deploy-actions -f ${{ runner.temp }}/config.hcl
              fi
          env:
              NOMAD_ADDR: ${{ inputs.nomad_addr }}
              NOMAD_TOKEN: ${{ inputs.nomad_token }}
              CONSUL_ADDR: ${{ inputs.consul_addr }}
              CONSUL_HTTP_TOKEN: ${{ inputs.consul_token }}
              NOMAD_CONFIG_FILE: ${{ inputs.config_file }}
              NOMAD_CONFIG: ${{ inputs.config }}
