name: Build AFFiNE

on:
    release:
        types: [created]
    workflow_dispatch:
    push:
        branches: [master]

concurrency:
    group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
    cancel-in-progress: true

jobs:
    deploy:
        runs-on: ubuntu-20.04
        environment: development
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Deploy to AFFiNE internal
              uses: toeverything/deploy-actions@master
              with:
                  tailscale_key: ${{ secrets.AFFINE_TAILSCALE_KEY }}
                  nomad_addr: ${{ secrets.AFFINE_NOMAD_ADDR }}
                  nomad_token: ${{ secrets.AFFINE_NOMAD_TOKEN }}
                  consul_addr: ${{ secrets.AFFINE_CONSUL_ADDR }}
                  consul_token: ${{ secrets.AFFINE_CONSUL_TOKEN }}
                  deploy_key: ${{ secrets.DEPLOY_ACTIONS_KEY }}
                  config: |
                      name = "alpha"
                      services = [
                          {
                              name  = "abbey-wood",
                              image = "ghcr.io/toeverything/affine-self-hosted",
                              tag   = "alpha-abbey-wood",
                              ports = [{ name = "abbey-wood", to = "3000" }],
                          }
                      ]
